variable "location" {
  description = "Azure region for the storage account."
  type        = string
}

variable "resource_group_name" {
  description = "Resource group name."
  type        = string
}

variable "sku_name" {
  description = "Storage account SKU."
  type        = string
  default     = "Standard_LRS"
}

variable "account_kind" {
  description = "Storage account kind."
  type        = string
  default     = "StorageV2"
}

variable "access_tier" {
  description = "Access tier for blob storage."
  type        = string
  default     = "Hot"
}

variable "min_tls_version" {
  description = "Minimum TLS version."
  type        = string
  default     = "TLS1_2"
}

variable "allow_blob_public_access" {
  description = "Allow public access to blobs."
  type        = bool
  default     = false
}

variable "vnet_id" {
  description = "VNet ID for private endpoints."
  type        = string
}

variable "subnet_id" {
  description = "Subnet ID for private endpoints."
  type        = string
}

variable "private_endpoints" {
  description = "List of storage services to create private endpoints for (e.g. [\"blob\", \"file\"])."
  type        = list(string)
  default     = []
}

variable "create_private_dns_zone" {
  description = "Whether to create and link private DNS zones for private endpoints."
  type        = bool
  default     = false
}

variable "blob_containers" {
  description = "List of blob containers to create. Each item is an object with name, public_access, metadata, etc."
  type = list(object({
    name           = string
    public_access  = optional(string)
    metadata       = optional(map(string))
    container_access_type = optional(string)
  }))
  default = []
}

variable "tables" {
  description = "List of tables to create. Each item is an object with name."
  type = list(object({
    name = string
  }))
  default = []
}

variable "queues" {
  description = "List of queues to create. Each item is an object with name and optional metadata."
  type = list(object({
    name     = string
    metadata = optional(map(string))
  }))
  default = []
}

variable "file_shares" {
  description = "List of file shares to create. Each item is an object with name, quota, and metadata."
  type = list(object({
    name     = string
    quota    = optional(number)
    metadata = optional(map(string))
  }))
  default = []
}

variable "storage_account_name" {
  description = "The name to use for the storage account (generated by the names module in main.tf)."
  type        = string
  default     = null
}

variable "log_analytics_workspace_id" {
  description = "Resource ID of the Log Analytics workspace for diagnostics"
  type        = string
}

variable "tags" {
  description = "A map of tags to assign to resources."
  type        = map(string)
}
